### ISSUE TITLE
Occasionally stops working

### ISSUE THREAD

**Issue by pljvp** [livestyle/issues#115]
Cannot find a pattern, but Livestyle regularly just doesn't sync my edits from Sublime to Chromium

Ubuntu 14.04 (64-bit)
Chromium Version 49.0.2623.108
Sublime 3103

Here's the log:

[21:59] this.ref.addProperty is not a function
TypeError: this.ref.addProperty is not a function
    at Object.o.addProperty (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/worker.js:481:6772)
    at Object.o.property (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/worker.js:481:6430)
    at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/worker.js:480:30662
    at Array.forEach (native)
    at Object.f.apply (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/worker.js:480:30400)
    at t.exports (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/worker.js:481:1119)
    at Function.t.exports.applyPatch (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/worker.js:480:1631)
    at Object.t.exports.patch (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/worker.js:481:30166)
    at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/worker.js:146:15
    at Array.forEach (native)

**Comment by sergeche** [comment]
Can you provide a sample source stylesheet? It looks like that LiveStyle is unable to update CSS code (either in browser or editor, depending on which side you’re making updates)
