### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by programmatix** [livestyle/issues#146]
Just downloaded latest Windows build and get 

2016-05-03 17:43:47> Program: Starting Squirrel Updater: --install .
2016-05-03 17:43:47> Program: Starting install, writing to C:\Users\Graham\AppData\Local\SquirrelTemp
2016-05-03 17:43:47> Program: About to install to: C:\Users\Graham\AppData\Local\launcher
2016-05-03 17:43:47> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Graham\AppData\Local\launcher\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-05-03 17:43:47> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Graham\AppData\Local\SquirrelTemp
2016-05-03 17:43:47> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-05-03 17:43:47> ApplyReleasesImpl: Writing files to app directory: C:\Users\Graham\AppData\Local\launcher\app-0.0.10
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\d3dcompiler_47.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\d3dcompiler_47.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\content_resources_200_percent.pak to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\content_resources_200_percent.pak
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\DuelystLauncher.exe to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\DuelystLauncher.exe
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\ffmpegsumo.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\ffmpegsumo.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\content_shell.pak to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\content_shell.pak
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\icudtl.dat to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\icudtl.dat
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\libEGL.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\libEGL.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\libGLESv2.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\libGLESv2.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\LICENSE to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\LICENSE
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\msvcp120.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\msvcp120.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\msvcr120.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\msvcr120.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\natives_blob.bin to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\natives_blob.bin
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\pdf.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\pdf.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\snapshot_blob.bin to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\snapshot_blob.bin
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\ui_resources_200_percent.pak to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\ui_resources_200_percent.pak
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\node.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\node.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\xinput1_3.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\xinput1_3.dll
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\squirrel.exe to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\squirrel.exe
2016-05-03 17:43:49> ApplyReleasesImpl: Moving file C:\Users\Graham\AppData\Local\launcher\app-0.0.10\lib\net45\vccorlib120.dll to C:\Users\Graham\AppData\Local\launcher\app-0.0.10\vccorlib120.dll
2016-05-03 17:43:50> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Graham\AppData\Local\launcher\app-0.0.10\DuelystLauncher.exe]
2016-05-03 17:43:51> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-05-03 17:43:51> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2016-05-03 17:43:51> ApplyReleasesImpl: Fixing up tray icons
2016-05-03 17:43:51> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.10
2016-05-03 17:43:51> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.10

**Comment by programmatix** [comment]
Ah I'm completely out of disk space.  May be worth checking for that in the installer.
