### ISSUE TITLE
Error when loading Sublime Text package

### ISSUE THREAD

**Issue by ghost** [livestyle/issues#158]
The Livestyle Chrome extension won't connect with my editor. When I launch Sublime Text 3, I see the following error in the console.

> reloading plugin LiveStyle.livestyle-plugin
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/andy/.config/sublime-text-3/Packages/LiveStyle/livestyle-plugin.py", line 23, in <module>
    import livestyle.server as server
  File "/home/andy/.config/sublime-text-3/Packages/LiveStyle/livestyle/server.py", line 15, in <module>
    import tornado.platform.epoll
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/andy/.config/sublime-text-3/Packages/LiveStyle/tornado.zip/tornado/platform/epoll.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/andy/.config/sublime-text-3/Packages/LiveStyle/tornado.zip/tornado/ioloop.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/andy/.config/sublime-text-3/Packages/LiveStyle/tornado.zip/tornado/concurrent.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/andy/.config/sublime-text-3/Packages/LiveStyle/tornado.zip/tornado/log.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/andy/.config/sublime-text-3/Packages/LiveStyle/tornado.zip/tornado/escape.py", line 41, in <module>
AttributeError: 'module' object has no attribute 'parse'

**Comment by pixelciosa** [comment]
I am having the same issue ending with "AttributeError: 'module' object has no attribute 'parse' " :( 
Any ideas or workaround?

**Comment by whryan** [comment]
Same issue here. Would love a fix if any has been found.

**Comment by pixelciosa** [comment]
Rollback properly the sublime text... For me,  on ubuntu, the version 3114 of Sublime Text worked... finally!

**Comment by ghost** [comment]
I'd rather not roll it back, 3143 has some features I rely on. So, before I do that, is there anyone who has Sublime Text 3143 installed who can get Livestyle to work? I guess if you can, you probably won't be browsing the issues here, but it's worth asking anyway.

**Comment by TheLastZombie** [comment]
@andyforceno I have 3143, and everything's working. On Windows, at least.

![image](https://user-images.githubusercontent.com/8181990/34645188-1d23aa82-f347-11e7-81e9-e77a30d28bbd.png)
