### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by xdpsee** [livestyle/issues#165]
macos: 10.14.6 (18G1012)
chrome: 79.0.3945.117

Uncaught Exception:
TypeError: Cannot read property 'nodeName' of null
    at Object.parse (/Applications/LiveStyle.app/Contents/Resources/app/node_modules/browser-launcher2/node_modules/plist/lib/parse.js:45:26)
    at /Applications/LiveStyle.app/Contents/Resources/app/node_modules/browser-launcher2/lib/darwin/util.js:13:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by sahandii** [comment]
I'm having the same error. Did you find any fix? Thx

**Comment by plancked** [comment]
same here!

**Comment by kalobkalob** [comment]
I'm having the same problem, was this forgotten?

**Comment by 1GR3** [comment]
+1
