### ISSUE TITLE
Error on Launch - MAC OSX

### ISSUE THREAD

**Issue by sweetyams** [livestyle/issues#67]
I am running the following:
MAC OS X El Capitain 10.11.1
Macbook Pro Retina 15" Early 2013

I receive the following error when I click the menu bar icon:
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: model.toJSON is not a function 
  at updateMainWindow (/Applications/Livestyle.app/Contents/Resources/app/main.js:79:24)
  at EventEmitter.<anonymous> (/Applications/Livestyle.app/Contents/Resources/app/main.js:37:19)
  at emitNone (events.js:67:13)
  atEventEmiiter.emit (events.js:166:7)
  at showWindow (/Applications/Livestyle.app/Contents/Resources/app/node_modules/menubar/index.js:107:15)
 at Tray.clickec(/Applications/Livestyle.app/Contents/Resources/app/node_modules/menubar/index.js:75:7)
  at emitTwo (events.js:87:13)
  at Tray.emit (events.js:172:7)

**Comment by sweetyams** [comment]
<img width="482" alt="screenshot 2015-12-04 09 44 37" src="https://cloud.githubusercontent.com/assets/1238170/11592466/93783f1c-9a6c-11e5-8096-87ff3a7436de.png">

**Comment by sergeche** [comment]
Can you open Console app and check if there are any errors related to LiveStyle?

**Comment by sweetyams** [comment]
Hey @sergeche, I just again and no error! - not sure what happened. I also checked console and it worked fine.

Thank you!

**Comment by sergeche** [comment]
I actually found the source of this error, it’s a good idea to re-download app to get rid of it.

**Comment by sweetyams** [comment]
Thanks Sergey, will do!
